### ISSUE TITLE
Tokenizer breaks at nested script tags

### ISSUE THREAD

**Issue by wesselvanderlinden** [nik-garmash/hyntax#13]
The tokenizer breaks on script tags when a `</script>` occurs somewhere in the script. For example:

```
const { tokens } = tokenize(`
<script>
  console.log("<script></script>")
</script>
`);
console.log(JSON.stringify(tokens, undefined, 2));
```

I would expect that the tokenizer will return a token for the script tag with the `content` set to:  `console.log("<script></script>")`. But instead it breaks the script's content at the `</script>` in the JS-string.

**Full output:**
```
[
  {
    "type": "token:text",
    "content": "\n",
    "startPosition": 0,
    "endPosition": 0
  },
  {
    "type": "token:open-tag-start-script",
    "content": "<script",
    "startPosition": 1,
    "endPosition": 7
  },
  {
    "type": "token:open-tag-end-script",
    "content": ">",
    "startPosition": 8,
    "endPosition": 8
  },
  {
    "type": "token:script-tag-content",
    "content": "\n  console.log(\"<script>",
    "startPosition": 9,
    "endPosition": 32
  },
  {
    "type": "token:close-tag-script",
    "content": "</script>",
    "startPosition": 33,
    "endPosition": 41
  },
  {
    "type": "token:text",
    "content": "\")\n",
    "startPosition": 42,
    "endPosition": 44
  },
  {
    "type": "token:close-tag",
    "content": "</script>",
    "startPosition": 45,
    "endPosition": 53
  },
  {
    "type": "token:text",
    "content": "\n",
    "startPosition": 54,
    "endPosition": 54
  }
]
```

**Comment by nik-garmash** [comment]
Hi, thank you for the report.

[HTML Specification](https://www.w3.org/TR/html50/scripting-1.html#restrictions-for-contents-of-script-elements) puts some restriction on `<script></script>` content, one of them is that nested script tags need to be escaped. 

Basically, HTML in your example is not valid. Look at how browsers parse the same markup

Chrome
<img width="342" alt="Screenshot 2019-07-19 at 10 47 03" src="https://user-images.githubusercontent.com/793851/61522414-9d7f2700-aa12-11e9-9473-d2cd8fd33ab6.png">

Safari
<img width="329" alt="Screenshot 2019-07-19 at 10 47 16" src="https://user-images.githubusercontent.com/793851/61522430-a243db00-aa12-11e9-9403-e90b343e3a1c.png">

It exactly matches the tokenizer output.

**Comment by nik-garmash** [comment]
Feel free to reopen the issue if you have some other thoughts on the topic.

**Comment by wesselvanderlinden** [comment]
@nik-garmash thanks for looking into it! Stupid of me to not test my code, I was testing out some edge cases and came across this one. I thought it was valid HTML, but now I see that you should escape the script tags inside JS code. So I tested that and hyntax handles that well :)

Thanks again!
