### ISSUE TITLE
Generate HTML from the AST?

### ISSUE THREAD

**Issue by matthewmueller** [nik-garmash/hyntax#3]
Hey thanks for putting this together. Unlike most of the other parsers, it doesn't shift tokens around.

Just wondering if you wrote the other side of this library yet? Generating HTML from a modified AST?

**Comment by nik-garmash** [comment]
Hi, I don't have a proper serializer, but here is [very simple implementation](https://github.com/nik-garmash/teig/blob/master/lib/serialize-node.js). You can copy-paste it to your project, for the time being, but once I have time I'll write tests for that code and add to as part of hyntax module.

**Comment by nik-garmash** [comment]
Close in favor of #15
